In [1]:
import pandas as pd

# Set pandas display rows to 500
pd.set_option('display.max_rows', 500)

In [2]:
data = pd.read_csv('./data/collated_data_amb.csv')
data.head().T

,0,1,2,3,4
LSOA,Welwyn Hatfield 010F,Welwyn Hatfield 012A,Welwyn Hatfield 002F,Welwyn Hatfield 002E,Welwyn Hatfield 010A
admissions,0.666667,4.0,2.0,0.666667,3.333333
closest_ivt_unit,SG14AB,SG14AB,SG14AB,SG14AB,SG14AB
closest_ivt_unit_time,18.7,19.8,18.7,18.7,18.7
closest_mt_unit,NW12BU,NW12BU,NW12BU,NW12BU,NW12BU
closest_mt_unit_time,36.9,36.9,38.0,36.9,36.9
closest_mt_transfer,CB20QQ,CB20QQ,CB20QQ,CB20QQ,CB20QQ
closest_mt_transfer_time,39.1,39.1,39.1,39.1,39.1
total_mt_time,57.8,58.9,57.8,57.8,57.8
ivt_rate,6.8,6.8,6.8,6.8,6.8
imd_2019_score,15.616,33.313,7.043,8.249,19.271
la_district_name_2019,Welwyn Hatfield,Welwyn Hatfield,Welwyn Hatfield,Welwyn Hatfield,Welwyn Hatfield
income_domain_score,0.104,0.176,0.037,0.066,0.113
income_domain_rank,17062,9058,31101,24030,15750
idaci_score,0.125,0.27,0.044,0.098,0.185
idaci_rank,17700,6329,30248,21078,11979
idaopi_score,0.186,0.269,0.055,0.064,0.12
idaopi_rank,11760,6337,29997,28181,18591
ethnic_group_all_categories_ethnic_group,1523,1637,1487,1665,1613
ethnic_group_white_total,1244,1249,1263,1333,1413
ethnic_group_white_english_welsh_scottish_northern_irish_british,1055,1014,1200,1155,1254
ethnic_group_white_irish,25,29,12,34,36
ethnic_group_white_gypsy_or_irish_traveller,1,2,0,1,1
ethnic_group_white_other_white,163,204,51,143,122
ethnic_group_mixed_multiple_ethnic_group_total,47,44,41,44,42
ethnic_group_mixed_multiple_ethnic_group_white_and_black_caribbean,17,13,14,12,18
ethnic_group_mixed_multiple_ethnic_group_white_and_black_african,7,9,5,4,3
ethnic_group_mixed_multiple_ethnic_group_white_and_asian,15,8,15,7,12
ethnic_group_mixed_multiple_ethnic_group_other_mixed,8,14,7,21,9
ethnic_group_asian_asian_british_total,113,168,110,198,99
ethnic_group_asian_asian_british_indian,31,73,51,125,42
ethnic_group_asian_asian_british_pakistani,10,7,12,14,2
ethnic_group_asian_asian_british_bangladeshi,14,28,17,6,17
ethnic_group_asian_asian_british_chinese,23,37,14,25,12
ethnic_group_asian_asian_british_other_asian,35,23,16,28,26
ethnic_group_black_african_caribbean_black_british_total,105,151,68,75,47
ethnic_group_black_african_caribbean_black_british_african,73,127,50,65,32
ethnic_group_black_african_caribbean_black_british_caribbean,30,11,13,10,11
ethnic_group_black_african_caribbean_black_british_other_black,2,13,5,0,4
ethnic_group_other_ethnic_group_total,14,25,5,15,12
ethnic_group_other_ethnic_group_arab,6,11,1,7,11
ethnic_group_other_ethnic_group_any_other_ethnic_group,8,14,4,8,1
all_categories_general_health,1523,1637,1487,1665,1613
very_good_or_good_health,1284,1269,1335,1494,1324
fair_health,175,265,115,143,210
bad_or_very_bad_health,64,103,37,28,79
all_categories_long_term_health_problem_or_disability,1523,1559,1469,1665,1613
day_to_day_activities_limited_a_lot,81,118,51,47,120
day_to_day_activities_limited_a_little,113,129,74,82,156
day_to_day_activities_not_limited,1329,1312,1344,1536,1337
rural_urban_2011,Urban city and town,Urban city and town,Urban city and town,Urban city and town,Urban city and town
population_all,1612,1900,1563,1848,1757
age_band_all_0,105,97,98,81,130
age_band_all_5,116,106,102,129,137
age_band_all_10,104,81,131,143,129
age_band_all_15,91,84,118,118,92
age_band_all_20,73,159,65,100,73
age_band_all_25,127,268,76,120,107
age_band_all_30,136,193,110,157,183
age_band_all_35,154,151,101,146,150
age_band_all_40,115,105,128,207,117
age_band_all_45,88,117,131,165,92
age_band_all_50,115,122,107,147,103
age_band_all_55,102,127,107,108,113
age_band_all_60,74,87,96,71,75
age_band_all_65,72,47,60,50,71
age_band_all_70,55,45,56,37,73
age_band_all_75,44,39,25,24,52
age_band_all_80,22,29,15,28,33
age_band_all_85,10,20,13,15,17
age_band_all_90,9,23,24,2,10
population_females,777,920,794,916,919
age_band_females_0,45,55,51,35,65
age_band_females_5,60,54,54,76,75
age_band_females_10,46,31,59,73,73
age_band_females_15,45,48,63,59,45
age_band_females_20,42,94,31,46,42
age_band_females_25,62,109,34,58,60
age_band_females_30,65,102,54,74,96
age_band_females_35,74,64,54,68,82
age_band_females_40,56,46,61,111,62
age_band_females_45,41,55,58,77,39
age_band_females_50,49,62,53,87,41
age_band_females_55,43,47,58,48,62
age_band_females_60,46,34,55,30,36
age_band_females_65,39,23,27,26,38
age_band_females_70,27,27,28,20,45
age_band_females_75,18,18,18,9,24
age_band_females_80,8,17,10,12,20
age_band_females_85,5,15,4,6,7
age_band_females_90,6,19,22,1,7
population_males,835,980,769,932,838
age_band_males_0,60,42,47,46,65
age_band_males_5,56,52,48,53,62
age_band_males_10,58,50,72,70,56
age_band_males_15,46,36,55,59,47
age_band_males_20,31,65,34,54,31
age_band_males_25,65,159,42,62,47
age_band_males_30,71,91,56,83,87
age_band_males_35,80,87,47,78,68
age_band_males_40,59,59,67,96,55
age_band_males_45,47,62,73,88,53
age_band_males_50,66,60,54,60,62
age_band_males_55,59,80,49,60,51
age_band_males_60,28,53,41,41,39
age_band_males_65,33,24,33,24,33
age_band_males_70,28,18,28,17,28
age_band_males_75,26,21,7,15,28
age_band_males_80,14,12,5,16,13
age_band_males_85,5,5,9,9,10
age_band_males_90,3,4,2,1,3
ambulance_service,East of England,East of England,East of England,East of England,East of England
local_authority_district_22,Welwyn Hatfield,Welwyn Hatfield,Welwyn Hatfield,Welwyn Hatfield,Welwyn Hatfield
LAD22NM,Welwyn Hatfield,Welwyn Hatfield,Welwyn Hatfield,Welwyn Hatfield,Welwyn Hatfield
country,England,England,England,England,England

In [3]:
census = pd.read_csv('./data/demographic/2011_Census_Data.csv')
census.head().T

,0,1,2,3,4
SOA Code,E01020723,E01020703,E01033164,E01033195,E01033197
SOA Name,County Durham 029C,County Durham 030A,County Durham 030D,County Durham 030E,County Durham 030F
LA Code,E06000047,E06000047,E06000047,E06000047,E06000047
Local Authority Name,County Durham,County Durham,County Durham,County Durham,County Durham
Supergroup Code,1,1,1,1,1
Supergroup Name,Cosmopolitan student neighbourhoods,Cosmopolitan student neighbourhoods,Cosmopolitan student neighbourhoods,Cosmopolitan student neighbourhoods,Cosmopolitan student neighbourhoods
Group Code,1a,1a,1a,1a,1a
Group Name,Cosmopolitan student neighbourhoods,Cosmopolitan student neighbourhoods,Cosmopolitan student neighbourhoods,Cosmopolitan student neighbourhoods,Cosmopolitan student neighbourhoods
% Persons living in a communal establishment,0.1,5.3,56.0,31.2,43.7
Number of persons per heactre,48.7,57.4,41.0,32.0,32.8
% Persons aged 0 to 4 years,4.4,1.2,0.7,1.9,0.5
% Persons aged 5 to 14 years,5.6,2.0,2.2,2.4,0.9
% Persons aged 25 to 44 years,26.1,11.6,11.0,13.3,19.9
% Persons aged 45 to 64 years,17.9,9.4,6.0,15.0,9.6
% Persons aged 65 to 89,13.1,8.4,5.1,12.1,9.1
% Persons aged 90 years and over,0.8,1.3,0.3,0.4,1.5
% Persons aged 16 and over who are single,57.5,78.8,87.2,68.6,78.6
% Persons aged 16 and over who are married or registered in a civil partnership,29.9,12.6,8.7,24.6,11.0
% Persons aged 16 and over who are divorced or separated,7.7,4.3,2.3,3.9,5.3
% Persons who are white,92.5,91.9,89.8,92.1,92.2
% Persons who have mixed ethnicity or are from multiple ethnic groups,1.7,2.7,3.2,2.0,2.1
% Persons who are Asian/Asian British: Indian,0.7,1.2,1.4,1.7,1.4
% Persons who are Asian/Asian British: Pakistani,0.0,0.3,0.3,0.1,0.4
% Persons who are Asian/Asian British: Bangladeshi,0.0,0.0,0.1,0.0,0.0
% Persons who are AsianAsian British: Chinese and Other,3.1,2.8,3.8,3.0,2.5
% Persons who are Black/Caribbean/Black British,0.6,0.4,0.6,0.6,0.7
% Persons who are Arab or from other ethnic groups,1.3,0.7,0.9,0.5,0.6
% Persons whose country of birth is the United Kingdom or Ireland,86.5,88.1,83.1,86.1,89.1
% Persons whose country of birth is in the old EU (pre 2004 accession countries),3.2,2.9,3.9,4.0,2.4
% Persons whose country of birth is the new EU (post 2004 accession countries),2.1,0.6,0.7,0.6,0.6
% Main language is not English and cannot speak English well or at all,0.8,0.1,0.3,0.1,0.0
% Households with no children,16.2,11.7,11.9,18.7,8.0
% Households with non-dependent children,7.0,1.4,2.1,3.9,4.0
% Households with full-time students,11.5,40.7,26.8,17.8,39.4
% Households who live in a detached house or bungalow,8.7,3.7,6.6,28.0,3.3
% Households who live in a semi-detached house or bungalow,24.7,4.8,5.8,17.9,15.5
% Households who live in a terrace house or end of terrace house,42.2,56.4,33.0,37.2,49.6
% Households who live in a flat,24.4,35.1,54.6,16.9,31.6
% Households who own or have shared ownership of property,35.5,23.2,34.4,57.7,31.4
% Households who are private renting,35.2,57.1,53.0,31.1,50.4
% Households who are social renting,29.0,18.7,6.2,8.8,17.2
% Occupancy room rating one or less rooms than required,6.9,15.0,18.3,6.6,18.0
Standard Illness ratio,113.0,72.4,44.0,63.3,123.9
% Persons providing unpaid care,7.6,4.7,4.3,7.1,6.0
"% Persons aged 16 and over whose highest level of qualification is Level 1, Level 2 or apprenticeship",16.8,7.6,8.0,7.8,18.2
% Persons aged 16 and over whose highest level of qualification is Level 3 qualifications,21.4,60.4,64.5,46.9,47.0
% Persons aged 16 and over whose highest level of qualification is Level 4 and above,38.7,22.9,21.5,38.7,15.7
% Persons aged 16 and over who are schoolchildren or full-time students,31.7,70.8,79.1,59.2,53.9
% Households with two or more cars,17.2,16.8,14.4,21.9,16.2
% Persons aged between 16 and 74 who use public transport to get to work,9.8,10.9,12.9,10.4,12.6
% Persons aged between 16 and 74 who use private transport transport to get to work,47.4,27.9,26.3,44.4,28.3
"% Persons aged between 16 and 74 who walk, cycle or use an alternative method of transport to get to work",37.9,53.6,55.4,37.1,52.4
% Employed persons aged between 16 and 74 who are unemployed,3.5,0.8,0.7,1.4,2.1
% Employed persons aged between 16 and 74 who are part-time,36.2,56.5,58.4,40.0,61.1
% Employed persons aged between 16 and 74 who are full-time,63.8,43.5,41.6,60.0,38.9
"% Employed persons aged between 16 and 74 who work in the agrivculture, forestry or fishing industries",0.0,0.2,0.0,0.2,0.0
"% Employed persons aged between 16 and 74 who work in the mining, quarrying or construction industries",3.6,0.9,0.7,1.7,4.2
% Employed persons aged between 16 and 74 who work in the transport or storage industries,5.5,2.4,3.8,4.4,1.7
"% Employed persons aged between 16 and 74 who work in the energy, water or air conditioining supply industries",1.6,0.9,0.0,1.5,0.3
% Employed persons aged between 16 and 74 who work in the wholesale and retail trade; repair of motor vehicles and motor cycle vehicles,12.2,11.8,10.0,6.6,8.7
% Employed persons aged between 16 and 74 who work in the transport or service industries,2.0,0.9,0.7,1.7,2.2
% Employed persons aged between 16 and 74 who work in the accommodation or food service activities industries,7.4,18.6,17.5,12.6,26.1
"% Employed persons aged between 16 and 74 who work in the informatiojn and communication or professional, scientific and technical acitivities industries",11.8,9.8,11.3,8.3,4.8
"% Employed persons aged between 16 and 74 who work in the financial, insurance or real estate industries`",2.3,2.2,2.9,2.7,3.1
% Employed persons aged between 16 and 74 who work in the administrative or support service activities industries,4.0,2.0,2.0,3.2,3.6
% Employed persons aged between 16 and 74 who work in the public administration or defence; compulsory or social security industries,6.4,4.9,2.7,4.6,9.0
% Employed persons aged between 16 and 74 who work in the education sector,25.7,30.6,28.6,35.0,24.6
% Employed persons aged between 16 and 74 who work in the human health and social work activities industries,8.5,8.0,7.7,11.2,5.0

In [4]:
cols_to_merge = [
    'SOA Name',
    'Supergroup Code',
    'Supergroup Name',
    'Group Name',
    'Group Code',
    '% Persons living in a communal establishment',
    'Number of persons per heactre',
    '% Persons aged 0 to 4 years',
    '% Persons aged 5 to 14 years',
    '% Persons aged 25 to 44 years',
    '% Persons aged 45 to 64 years',
    '% Persons aged 65 to 89',
    '% Persons aged 90 years and over',
    '% Persons aged 16 and over who are single',
    '% Persons aged 16 and over who are married or registered in a civil partnership',
    '% Persons aged 16 and over who are divorced or separated',
    '% Persons who are white',
    '% Households who live in a detached house or bungalow',
    '% Households who live in a semi-detached house or bungalow',
    '% Households who live in a terrace house or end of terrace house',
    '% Households who live in a flat',
    '% Households who own or have shared ownership of property',
    '% Households who are private renting',
    '% Households who are social renting',
    'Standard Illness ratio',
    '% Persons providing unpaid care',
    '% Persons aged 16 and over whose highest level of qualification is Level 1, Level 2 or apprenticeship',
    '% Persons aged 16 and over whose highest level of qualification is Level 3 qualifications',
    '% Persons aged 16 and over whose highest level of qualification is Level 4 and above',
    '% Persons aged 16 and over who are schoolchildren or full-time students',
    '% Households with two or more cars',
    '% Persons aged between 16 and 74 who use public transport to get to work',
    '% Persons aged between 16 and 74 who use private transport transport to get to work',
    '% Persons aged between 16 and 74 who walk, cycle or use an alternative method of transport to get to work',
    '% Employed persons aged between 16 and 74 who are unemployed',
    '% Employed persons aged between 16 and 74 who are part-time',
    '% Employed persons aged between 16 and 74 who are full-time',
]

merged_data = data.merge(census[cols_to_merge], left_on='LSOA', right_on='SOA Name', how='left')
# remove soa name
merged_data.drop('SOA Name', axis=1, inplace=True)

In [5]:
merged_data.head()
merged_data.to_csv('./data/collated_data_amb_census.csv', index=False)